/*
Web Application Firewall API

Testing WAFApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package waf

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_waf_WAFApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WAFApiService GetWAFDomains", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var wafId int64

		resp, httpRes, err := apiClient.WAFApi.GetWAFDomains(context.Background(), wafId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WAFApiService GetWAFEvents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var wafId int64

		resp, httpRes, err := apiClient.WAFApi.GetWAFEvents(context.Background(), wafId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
