/*
Services API

Azion Services

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateResourceRequest struct for UpdateResourceRequest
type UpdateResourceRequest struct {
	Content *string `json:"content,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	Name *string `json:"name,omitempty"`
	Trigger *string `json:"trigger,omitempty"`
}

// NewUpdateResourceRequest instantiates a new UpdateResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceRequest() *UpdateResourceRequest {
	this := UpdateResourceRequest{}
	return &this
}

// NewUpdateResourceRequestWithDefaults instantiates a new UpdateResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceRequestWithDefaults() *UpdateResourceRequest {
	this := UpdateResourceRequest{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetContent() string {
	if o == nil || o.Content == nil {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetContentOk() (*string, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *UpdateResourceRequest) SetContent(v string) {
	o.Content = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetContentType() string {
	if o == nil || o.ContentType == nil {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || o.ContentType == nil {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasContentType() bool {
	if o != nil && o.ContentType != nil {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *UpdateResourceRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateResourceRequest) SetName(v string) {
	o.Name = &v
}

// GetTrigger returns the Trigger field value if set, zero value otherwise.
func (o *UpdateResourceRequest) GetTrigger() string {
	if o == nil || o.Trigger == nil {
		var ret string
		return ret
	}
	return *o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceRequest) GetTriggerOk() (*string, bool) {
	if o == nil || o.Trigger == nil {
		return nil, false
	}
	return o.Trigger, true
}

// HasTrigger returns a boolean if a field has been set.
func (o *UpdateResourceRequest) HasTrigger() bool {
	if o != nil && o.Trigger != nil {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given string and assigns it to the Trigger field.
func (o *UpdateResourceRequest) SetTrigger(v string) {
	o.Trigger = &v
}

func (o UpdateResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.ContentType != nil {
		toSerialize["content_type"] = o.ContentType
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Trigger != nil {
		toSerialize["trigger"] = o.Trigger
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateResourceRequest struct {
	value *UpdateResourceRequest
	isSet bool
}

func (v NullableUpdateResourceRequest) Get() *UpdateResourceRequest {
	return v.value
}

func (v *NullableUpdateResourceRequest) Set(val *UpdateResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceRequest(val *UpdateResourceRequest) *NullableUpdateResourceRequest {
	return &NullableUpdateResourceRequest{value: val, isSet: true}
}

func (v NullableUpdateResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


