/*
 * Azion API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BadRequestResponse struct {
	Name []string `json:"name,omitempty"`
	IsActive []string `json:"is_active,omitempty"`
	Domains []string `json:"domains,omitempty"`
	EdgeFunctionsEnabled []string `json:"edge_functions_enabled,omitempty"`
	NetworkProtectionEnabled []string `json:"network_protection_enabled,omitempty"`
	WafEnabled []string `json:"waf_enabled,omitempty"`
}
