/*
 * Azion API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateEdgeFirewallRequest struct {
	Name string `json:"name,omitempty"`
	Domains []int32 `json:"domains,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	EdgeFunctionsEnabled bool `json:"edge_functions_enabled,omitempty"`
	NetworkProtectionEnabled bool `json:"network_protection_enabled,omitempty"`
	WafEnabled bool `json:"waf_enabled,omitempty"`
}
