/*
Object Storage

REST API OpenAPI documentation for the Object Storage

API version: 1.0.0 (v1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the PatchedBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBucket{}

// PatchedBucket struct for PatchedBucket
type PatchedBucket struct {
	Name *string `json:"name,omitempty"`
	EdgeAccess *EdgeAccessEnum `json:"edge_access,omitempty"`
}

// NewPatchedBucket instantiates a new PatchedBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBucket() *PatchedBucket {
	this := PatchedBucket{}
	return &this
}

// NewPatchedBucketWithDefaults instantiates a new PatchedBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBucketWithDefaults() *PatchedBucket {
	this := PatchedBucket{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedBucket) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBucket) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedBucket) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedBucket) SetName(v string) {
	o.Name = &v
}

// GetEdgeAccess returns the EdgeAccess field value if set, zero value otherwise.
func (o *PatchedBucket) GetEdgeAccess() EdgeAccessEnum {
	if o == nil || IsNil(o.EdgeAccess) {
		var ret EdgeAccessEnum
		return ret
	}
	return *o.EdgeAccess
}

// GetEdgeAccessOk returns a tuple with the EdgeAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBucket) GetEdgeAccessOk() (*EdgeAccessEnum, bool) {
	if o == nil || IsNil(o.EdgeAccess) {
		return nil, false
	}
	return o.EdgeAccess, true
}

// HasEdgeAccess returns a boolean if a field has been set.
func (o *PatchedBucket) HasEdgeAccess() bool {
	if o != nil && !IsNil(o.EdgeAccess) {
		return true
	}

	return false
}

// SetEdgeAccess gets a reference to the given EdgeAccessEnum and assigns it to the EdgeAccess field.
func (o *PatchedBucket) SetEdgeAccess(v EdgeAccessEnum) {
	o.EdgeAccess = &v
}

func (o PatchedBucket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.EdgeAccess) {
		toSerialize["edge_access"] = o.EdgeAccess
	}
	return toSerialize, nil
}

type NullablePatchedBucket struct {
	value *PatchedBucket
	isSet bool
}

func (v NullablePatchedBucket) Get() *PatchedBucket {
	return v.value
}

func (v *NullablePatchedBucket) Set(val *PatchedBucket) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBucket) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBucket(val *PatchedBucket) *NullablePatchedBucket {
	return &NullablePatchedBucket{value: val, isSet: true}
}

func (v NullablePatchedBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


