/*
Intelligent DNS

Azion Intelligent DNS API

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package idns

import (
	"encoding/json"
)

// GetZoneModel Object returned by get zone
type GetZoneModel struct {
	// The schema version
	SchemaVersion *int32 `json:"schema_version,omitempty"`
	Results *Zone `json:"results,omitempty"`
}

// NewGetZoneModel instantiates a new GetZoneModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetZoneModel() *GetZoneModel {
	this := GetZoneModel{}
	return &this
}

// NewGetZoneModelWithDefaults instantiates a new GetZoneModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetZoneModelWithDefaults() *GetZoneModel {
	this := GetZoneModel{}
	return &this
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *GetZoneModel) GetSchemaVersion() int32 {
	if o == nil || isNil(o.SchemaVersion) {
		var ret int32
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetZoneModel) GetSchemaVersionOk() (*int32, bool) {
	if o == nil || isNil(o.SchemaVersion) {
    return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *GetZoneModel) HasSchemaVersion() bool {
	if o != nil && !isNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given int32 and assigns it to the SchemaVersion field.
func (o *GetZoneModel) SetSchemaVersion(v int32) {
	o.SchemaVersion = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetZoneModel) GetResults() Zone {
	if o == nil || isNil(o.Results) {
		var ret Zone
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetZoneModel) GetResultsOk() (*Zone, bool) {
	if o == nil || isNil(o.Results) {
    return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetZoneModel) HasResults() bool {
	if o != nil && !isNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given Zone and assigns it to the Results field.
func (o *GetZoneModel) SetResults(v Zone) {
	o.Results = &v
}

func (o GetZoneModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	if !isNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableGetZoneModel struct {
	value *GetZoneModel
	isSet bool
}

func (v NullableGetZoneModel) Get() *GetZoneModel {
	return v.value
}

func (v *NullableGetZoneModel) Set(val *GetZoneModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetZoneModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetZoneModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetZoneModel(val *GetZoneModel) *NullableGetZoneModel {
	return &NullableGetZoneModel{value: val, isSet: true}
}

func (v NullableGetZoneModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetZoneModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


