/*
Edge Application API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgeapplications

import (
	"encoding/json"
)

// checks if the CreateRulesEngineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRulesEngineRequest{}

// CreateRulesEngineRequest struct for CreateRulesEngineRequest
type CreateRulesEngineRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Criteria [][]RulesEngineCriteria `json:"criteria"`
	Behaviors []RulesEngineBehavior `json:"behaviors"`
}

// NewCreateRulesEngineRequest instantiates a new CreateRulesEngineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRulesEngineRequest(name string, criteria [][]RulesEngineCriteria, behaviors []RulesEngineBehavior) *CreateRulesEngineRequest {
	this := CreateRulesEngineRequest{}
	this.Name = name
	this.Criteria = criteria
	this.Behaviors = behaviors
	return &this
}

// NewCreateRulesEngineRequestWithDefaults instantiates a new CreateRulesEngineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRulesEngineRequestWithDefaults() *CreateRulesEngineRequest {
	this := CreateRulesEngineRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateRulesEngineRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRulesEngineRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRulesEngineRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateRulesEngineRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRulesEngineRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateRulesEngineRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateRulesEngineRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCriteria returns the Criteria field value
func (o *CreateRulesEngineRequest) GetCriteria() [][]RulesEngineCriteria {
	if o == nil {
		var ret [][]RulesEngineCriteria
		return ret
	}

	return o.Criteria
}

// GetCriteriaOk returns a tuple with the Criteria field value
// and a boolean to check if the value has been set.
func (o *CreateRulesEngineRequest) GetCriteriaOk() ([][]RulesEngineCriteria, bool) {
	if o == nil {
		return nil, false
	}
	return o.Criteria, true
}

// SetCriteria sets field value
func (o *CreateRulesEngineRequest) SetCriteria(v [][]RulesEngineCriteria) {
	o.Criteria = v
}

// GetBehaviors returns the Behaviors field value
func (o *CreateRulesEngineRequest) GetBehaviors() []RulesEngineBehavior {
	if o == nil {
		var ret []RulesEngineBehavior
		return ret
	}

	return o.Behaviors
}

// GetBehaviorsOk returns a tuple with the Behaviors field value
// and a boolean to check if the value has been set.
func (o *CreateRulesEngineRequest) GetBehaviorsOk() ([]RulesEngineBehavior, bool) {
	if o == nil {
		return nil, false
	}
	return o.Behaviors, true
}

// SetBehaviors sets field value
func (o *CreateRulesEngineRequest) SetBehaviors(v []RulesEngineBehavior) {
	o.Behaviors = v
}

func (o CreateRulesEngineRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRulesEngineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["criteria"] = o.Criteria
	toSerialize["behaviors"] = o.Behaviors
	return toSerialize, nil
}

type NullableCreateRulesEngineRequest struct {
	value *CreateRulesEngineRequest
	isSet bool
}

func (v NullableCreateRulesEngineRequest) Get() *CreateRulesEngineRequest {
	return v.value
}

func (v *NullableCreateRulesEngineRequest) Set(val *CreateRulesEngineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRulesEngineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRulesEngineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRulesEngineRequest(val *CreateRulesEngineRequest) *NullableCreateRulesEngineRequest {
	return &NullableCreateRulesEngineRequest{value: val, isSet: true}
}

func (v NullableCreateRulesEngineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRulesEngineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


