/*
Digital Certificates API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digital_certificates

import (
	"encoding/json"
)

// checks if the DC403 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DC403{}

// DC403 struct for DC403
type DC403 struct {
	Errors []map[string]interface{} `json:"errors,omitempty"`
	SchemaVersion *int32 `json:"schema_version,omitempty"`
}

// NewDC403 instantiates a new DC403 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDC403() *DC403 {
	this := DC403{}
	return &this
}

// NewDC403WithDefaults instantiates a new DC403 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDC403WithDefaults() *DC403 {
	this := DC403{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *DC403) GetErrors() []map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DC403) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *DC403) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *DC403) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *DC403) GetSchemaVersion() int32 {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret int32
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DC403) GetSchemaVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *DC403) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given int32 and assigns it to the SchemaVersion field.
func (o *DC403) SetSchemaVersion(v int32) {
	o.SchemaVersion = &v
}

func (o DC403) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DC403) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schema_version"] = o.SchemaVersion
	}
	return toSerialize, nil
}

type NullableDC403 struct {
	value *DC403
	isSet bool
}

func (v NullableDC403) Get() *DC403 {
	return v.value
}

func (v *NullableDC403) Set(val *DC403) {
	v.value = val
	v.isSet = true
}

func (v NullableDC403) IsSet() bool {
	return v.isSet
}

func (v *NullableDC403) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDC403(val *DC403) *NullableDC403 {
	return &NullableDC403{value: val, isSet: true}
}

func (v NullableDC403) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDC403) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


