/*
Purge API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package realtimepurge

import (
	"encoding/json"
)

// checks if the PurgeUrlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurgeUrlRequest{}

// PurgeUrlRequest struct for PurgeUrlRequest
type PurgeUrlRequest struct {
	Urls []string `json:"urls"`
	Method string `json:"method"`
}

// NewPurgeUrlRequest instantiates a new PurgeUrlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurgeUrlRequest(urls []string, method string) *PurgeUrlRequest {
	this := PurgeUrlRequest{}
	this.Urls = urls
	this.Method = method
	return &this
}

// NewPurgeUrlRequestWithDefaults instantiates a new PurgeUrlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurgeUrlRequestWithDefaults() *PurgeUrlRequest {
	this := PurgeUrlRequest{}
	return &this
}

// GetUrls returns the Urls field value
func (o *PurgeUrlRequest) GetUrls() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value
// and a boolean to check if the value has been set.
func (o *PurgeUrlRequest) GetUrlsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Urls, true
}

// SetUrls sets field value
func (o *PurgeUrlRequest) SetUrls(v []string) {
	o.Urls = v
}

// GetMethod returns the Method field value
func (o *PurgeUrlRequest) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *PurgeUrlRequest) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *PurgeUrlRequest) SetMethod(v string) {
	o.Method = v
}

func (o PurgeUrlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurgeUrlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["urls"] = o.Urls
	toSerialize["method"] = o.Method
	return toSerialize, nil
}

type NullablePurgeUrlRequest struct {
	value *PurgeUrlRequest
	isSet bool
}

func (v NullablePurgeUrlRequest) Get() *PurgeUrlRequest {
	return v.value
}

func (v *NullablePurgeUrlRequest) Set(val *PurgeUrlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePurgeUrlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePurgeUrlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurgeUrlRequest(val *PurgeUrlRequest) *NullablePurgeUrlRequest {
	return &NullablePurgeUrlRequest{value: val, isSet: true}
}

func (v NullablePurgeUrlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurgeUrlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


